version: '3.7'

volumes:
  var-lib-ldap:
  etc-ldap-slapd:
  container-service-slapd-assests-certs:
  var-lib-ldap.secAuthority:
  var-lib-postgresql-cert:
  var-lib-postgresql-data:
  var-shared:
  var-application.logs:

services:
  openldap:
    image: icr.io/isva/verify-access-openldap:${VERSION}
    container_name: openldap-${VERSION}
    environment:
      LDAP_LOG_LEVEL: "3"
      LDAP_ORGANISATION: "$ORG_NAME"
      LDAP_DOMAIN: "$DOMAIN_NAME"
      LDAP_BASE_DN: "dc=$DC1,dc=$DC2"
      LDAP_ADMIN_PASSWORD: "$PASSWORD"
      LDAP_CONFIG_PASSWORD: "$PASSWORD"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "$PASSWORD"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1"
      LDAP_TLS_PROTOCOL_MIN: "3.3"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_ENABLE_PORT_389: "true"
    tty: true
    stdin_open: true
    volumes:
      - var-lib-ldap:/var/lib/ldap
      - etc-ldap-slapd:/etc/ldap/slapd.d
      - container-service-slapd-assests-certs:/container/service/slapd/assets/certs:rw
      - var-lib-ldap.secAuthority:/var/lib/ldap.secAuthority
    expose:
      - "389"
      - "636"
    ports:
      - 0.0.0.0:${LDAP_PORT}:389
      - 0.0.0.0:${LDAPS_PORT}:636
    domainname: "$DOMAIN_NAME"
    hostname: "openldap"

  postgresql:
    image: icr.io/isva/verify-access-postgresql:${VERSION}
    container_name: postgresql-${VERSION}
    environment:
      POSTGRES_CERT_DN: "/CN=postgresql"
      POSTGRES_UNSECURE: "false"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "$PASSWORD"
      POSTGRES_DB: "isva"
    tty: true
    stdin_open: true
    volumes:
      - var-lib-postgresql-cert:/var/lib/postgresql/cert:rw
      - var-lib-postgresql-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - 0.0.0.0:${POSTGRESQL_PORT}:5432
    domainname: "$DOMAIN_NAME"
    hostname: "postgresql"
    depends_on:
      - openldap

  isvaconfig:
    image: icr.io/isva/verify-access:${ISAM_VERSION}
    container_name: isvaconfig-${ISAM_VERSION}
    environment:
      - CONTAINER_TIMEZONE=${TZ}
      - SERVICE=config
      - ADMIN_PWD=${PASSWORD}
      - USE_CONTAINER_LOG_DIR=1
    volumes:
      - var-shared:/var/shared
      - var-application.logs:/var/application.logs
    ports:
      - 0.0.0.0:$LMI_PORT:9443
    expose:
      - "9443"
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE
    depends_on:
      - openldap
      - postgresql
    domainname: "$DOMAIN_NAME"
    hostname: "isvaconfig"

  isvadscone:
    image: icr.io/isva/verify-access-dsc:${ISAM_VERSION}
    container_name: isvadscone-${ISAM_VERSION}
    environment:
      - CONTAINER_TIMEZONE=America/Chicago
      - SERVICE=dsc
      - INSTANCE=1
      - CONFIG_SERVICE_URL=https://isvaconfig:9443/shared_volume
      - CONFIG_SERVICE_USER_NAME=cfgsvc
      - CONFIG_SERVICE_USER_PWD=${PASSWORD}
      - AUTO_RELOAD_FREQUENCY=30
      - USE_CONTAINER_LOG_DIR=1
    volumes:
      - var-shared:/var/shared
      - var-application.logs:/var/application.logs
    expose:
      - "443"
      - "444"
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE
    depends_on:
      - isvaconfig
    domainname: "$DOMAIN_NAME"
    hostname: "isvadscone"

  isvaruntimeone:
    image: icr.io/isva/verify-access-runtime:${ISAM_VERSION}
    container_name: isvaruntimeone-${ISAM_VERSION}
    environment:
      - CONTAINER_TIMEZONE=America/Chicago
      - SERVICE=runtime
      - CONFIG_SERVICE_URL=https://isvaconfig:9443/shared_volume
      - CONFIG_SERVICE_USER_NAME=cfgsvc
      - CONFIG_SERVICE_USER_PWD=${PASSWORD}
      - AUTO_RELOAD_FREQUENCY=30
      - USE_CONTAINER_LOG_DIR=1
    volumes:
      - var-shared:/var/shared
      - var-application.logs:/var/application.logs
    expose:
      - "9443"
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE
    depends_on:
      - isvadscone
    domainname: "$DOMAIN_NAME"
    hostname: "isvaruntimeone"
    
  isvarpone:
    image: icr.io/isva/verify-access-wrp:${ISAM_VERSION}
    container_name: isvarpone-${ISAM_VERSION}
    environment:
      - CONTAINER_TIMEZONE=America/Chicago
      - SERVICE=webseal
      - INSTANCE=default
      - CONFIG_SERVICE_URL=https://isvaconfig:9443/shared_volume
      - CONFIG_SERVICE_USER_NAME=cfgsvc
      - CONFIG_SERVICE_USER_PWD=${PASSWORD}
      - AUTO_RELOAD_FREQUENCY=30
      - USE_CONTAINER_LOG_DIR=1
    volumes:
      - var-shared:/var/shared
      - var-application.logs:/var/application.logs
    expose:
      - "9443"
    ports:
      - 0.0.0.0:$ONE_HTTPS_PORT:9443
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE
    depends_on:
      - isvaruntimeone
    domainname: "$DOMAIN_NAME"
    hostname: "isvarpone"
