#!/bin/sh
# Author: Nick Lloyd
#
# History:
#
# 2021-03-21: Initial version.
#

RRD_FILE=$1
DATE=`date +"%Y-%m-%d-%H-%M-%S"`

rrdtool graph $RRD_FILE.png --imgformat PNG -w 1024 -h 760 --start now-90d --end now 				\
		--title "Appliance Disk Usage" --watermark "Generated by ISVA Support RRD Grapher v1.0 on $DATE" 		\
		DEF:root=$RRD_FILE:root:MAX   LINE2:root#FF0000:"ROOT"	\
		DEF:boot=$RRD_FILE:boot:MAX   LINE2:boot#000000:"BOOT"
