#!/bin/sh
# Author: Nick Lloyd
#
# History:
#
# 2021-03-21: Initial version.
#

RRD_FILE=$1
DATE=`date +"%Y-%m-%d-%H-%M-%S"`

rrdtool graph $RRD_FILE.png --imgformat PNG -w 1024 -h 760 --start now-30d --end now 				\
		--title "Appliance Memory Usage" --watermark "Generated by ISVA Support RRD Grapher v1.0 on $DATE" 		\
		DEF:memoryused=$RRD_FILE:memoryused:MAX   LINE2:memoryused#FF0000:"Percent of Memory Used"

exit $?
